# Generated by Django 6.0.4 on 2026-05-31 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True, verbose_name='Nomor Kamar')),
                ('room_type', models.CharField(choices=[('Reguler', 'Reguler (Kamar Mandi Luar)'), ('Eksklusif', 'Eksklusif (Kamar Mandi Dalam + AC)'), ('VIP', 'VIP (Fasilitas Lengkap + Water Heater)')], default='Reguler', max_length=20, verbose_name='Tipe Kamar')),
                ('price_per_month', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Harga per Bulan (Rp)')),
                ('facilities', models.TextField(verbose_name='Fasilitas')),
                ('is_available', models.BooleanField(default=True, verbose_name='Tersedia')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Foto Kamar')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=100, verbose_name='Nama Lengkap')),
                ('tenant_phone', models.CharField(max_length=15, verbose_name='Nomor WhatsApp/HP')),
                ('tenant_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('duration_months', models.IntegerField(default=1, verbose_name='Durasi Sewa (Bulan)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan Tambahan')),
                ('status', models.CharField(choices=[('Pending', 'Menunggu Konfirmasi'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Pending', max_length=20, verbose_name='Status Pengajuan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rooms.room', verbose_name='Kamar')),
            ],
        ),
    ]
