# Generated by Django 6.0.4 on 2026-05-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_proof',
            field=models.ImageField(default='', upload_to='proofs/', verbose_name='Bukti Transfer DP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Foto Kamar (Opsional)'),
        ),
    ]
